default: &default
  enable_asset_creation: true
  enable_first_time_user_exp: true
  enable_tag_modification: true
  feedback_slack:
    endpoint: "#endpoint"
    channel_name: "#channel_name"

development:
  enable_asset_creation: true
  enable_first_time_user_exp: true
  enable_tag_modification: true
  <<: *default

test:
  enable_asset_creation: true
  enable_first_time_user_exp: true
  enable_tag_modification: true
  <<: *default

production:
  enable_asset_creation: true
  enable_first_time_user_exp: true
  enable_tag_modification: true
  feedback_slack:
    endpoint: "https://hooks.slack.com/services/xxx" #put your slack token here upon deployment - don't put slack tokens in public repos ;)
    channel_name: "#techmaturity"
